### ISSUE TITLE
Variable assignment adds values to the stack in an inconsistent manner

### ISSUE THREAD

**Issue by kms70847** [morganthrapp/Pylons-lang#1]
The following program:

```
[C0]
```

Has the output

```
[0]
```

But I expected it to be

```
[]
```

---

Alternatively, if "the result of an assignment is added to the stack" is intended behavior, then the following program:

```
[C00+]
```

Has the output

```
[]
```

But I would expect it to be

```
[0]
```

**Comment by morganthrapp** [comment]
Yup, your assumptions are right. There seems to be a bug in variable parsing.

**Comment by morganthrapp** [comment]
This is fixed in https://github.com/morganthrapp/Pylons-lang/commit/eddca12f306ff1c9b28a76137154be8b99f79306
